### ISSUE TITLE
"Clear Selection" on home tab clears selected geography but not selected variables

### ISSUE THREAD

**Issue by gummybirdy** [GeoDaCenter/OpenAirQ-dashboard#1]
Found a bit of unintuitive behavior while going over the dash; clearing the selection on the home tab does clear the selected geography, but as far as I can tell, there is no way to clear the variables selected in the plotly element. Intuitively, I expected clear selection to clear both variables and the selected regions.

**Comment by yahmskeano** [comment]
Fixed in 3d017d18b4f45ac0c5ac48a57dc9f64e354b852d
