### ISSUE TITLE
Time bars are not dynamic

### ISSUE THREAD

**Issue by nofurtherinformation** [GeoDaCenter/OpenAirQ-dashboard#18]

**Comment by QWL55** [comment]
I updated the data source that we use to create the time bars. The changes are reflected in the locally deployed app but not the cloud-hosted app. It seems that we need to add R packages in the script I just pushed into the Github Action flow

**Comment by nofurtherinformation** [comment]
Hey @QWL55 ! You can add packages to the [Dockerfile](https://github.com/GeoDaCenter/OpenAirQ-dashboard/blob/master/Dockerfile) for use when the Github Action flow builds the docker image (to upload to shinyapps). For additional Github actions, if there are lots of (or large) packages that are only for data wrangling, we can make a second docker image!

**Comment by andrewjmorse** [comment]
Fixed/migrated to #20 and #21
