### ISSUE TITLE
Request: spatiotemporal aggregations

### ISSUE THREAD

**Issue by andrewjmorse** [GeoDaCenter/OpenAirQ-dashboard#2]
Per city: Desire to have different levels of spatial/temporal aggregations (incl. as vector), and the ability to compare between them; also consideration of different summary stats, e.g. max/mean

**Comment by yahmskeano** [comment]
Time slider and region selection capability added to Region Explorer. This gives some amount of control over spatiotemporal aggregations and also provides simple distributional plots/figures (eg min/max/median) for selected variables.

Added as of ea95676c8a4b787ded23a59903727139758cc5bd
